/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerEnv src/worker-configuration.d.ts` (hash: 0ab9383eeb849addc9bcb193b1bac49d)
interface __BaseEnv_WorkerEnv {
	OGC_CATALOG: KVNamespace;
	GEOBS_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEOBS_API_KEY">> {}
}
